on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: okteto-deploy

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate personal namespace"
        uses: okteto/namespace@master
        with:
          name: amitrangra

      - name: "Create deployment"
        uses: okteto/apply@master
        with:
          manifest: deployment.yaml